version: "3.8"

services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    # env_file: .env
    ports:
      - 42421:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: hiverlab
      MONGO_INITDB_ROOT_PASSWORD: hiverlab
      MONGO_INITDB_DATABASE: data-handler
    volumes:
      - db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    logging:
      driver: "none"

  # mongo-express:
    # image: mongo-express
    # restart: unless-stopped
    # ports:
      # - 42422:8081
    # env_file: .env
    # environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: hiverlab
      # ME_CONFIG_MONGODB_ADMINPASSWORD: hiverlab
    # logging:
     # driver: "none"
      
  app:
    image: data-handler
    depends_on:
      - mongodb
    restart: unless-stopped
    # env_file: .env
    build: /
    ports:
      - 42423:42423
    environment:
      DB_HOST: mongodb
      DB_USER: hiverlab
      DB_PASSWORD: hiverlab
      DB_NAME: data-handler
      DB_PORT: 27017

volumes:
  db: